# Generated by Django 4.1.7 on 2023-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_frainds'),
    ]

    operations = [
        migrations.AddField(
            model_name='frainds',
            name='friends',
            field=models.ManyToManyField(blank=True, to='app.frainds'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='Resource/users'),
        ),
    ]
