# Generated by Django 4.1.7 on 2023-04-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
