# Generated by Django 4.1.7 on 2023-04-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7000)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversation', to='app.room')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='members',
            field=models.ManyToManyField(blank=True, to='app.conversation'),
        ),
    ]
