# Generated by Django 4.1.7 on 2023-04-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_members_profile_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='Resource/users'),
        ),
    ]
