# Generated by Django 4.1.7 on 2023-04-27 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_message_reciver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=7000),
            preserve_default=False,
        ),
    ]
